# Generated by Django 5.1.2 on 2024-11-04 19:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Invitation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, verbose_name="Nombre del invitado"
                    ),
                ),
                ("message", models.TextField(verbose_name="Mensaje")),
                ("amount", models.IntegerField(verbose_name="Cupos")),
                ("code", models.UUIDField(default=uuid.uuid4, editable=False)),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creado el"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Actualizado el"),
                ),
                (
                    "last_modified_by",
                    models.CharField(
                        max_length=100, verbose_name="Último modificado por"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Confirmation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("will_attend", models.BooleanField(verbose_name="Asistirá")),
                (
                    "food_restrictions",
                    models.TextField(verbose_name="Restricciones alimenticias"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creado el"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Actualizado el"),
                ),
                (
                    "last_modified_by",
                    models.CharField(
                        max_length=100, verbose_name="Último modificado por"
                    ),
                ),
                (
                    "invitation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="invitations.invitation",
                    ),
                ),
            ],
        ),
    ]
