# Generated by Django 5.1.2 on 2024-11-04 19:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("invitations", "0002_alter_invitation_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invitation",
            name="code",
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
