# Generated by Django 5.1.2 on 2024-11-16 22:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("invitations", "0003_alter_invitation_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="invitation",
            name="expiration_date",
            field=models.DateField(
                default="2024-01-01", verbose_name="Fecha de expiración"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="invitation",
            name="is_honorary_invitation",
            field=models.BooleanField(
                default=False, verbose_name="Invitación honorífica"
            ),
        ),
        migrations.AlterField(
            model_name="invitation",
            name="message",
            field=models.TextField(blank=True, null=True, verbose_name="Mensaje"),
        ),
    ]
